version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.10"
  INSTALL_NODE_VERSION: "18.16.0"

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./dev.db:/tmp/dev.db
    - ./seed_factory_data.json:/app/data/seed_factory_data.json
    - ./seed_sprocket_types.json:/app/data/seed_sprocket_types.json

services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "sprocket_factory-development"
    depends_on:
      - db
    ports:
      - "8080:5000"
      - "2992:2992"
    <<: *default_volumes
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "sprocket_factory-production"
    ports:
      - "8080:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "sprocket_factory-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

volumes:
  node-modules:
